#!/usr/bin/bash

clear && adb reboot bootloader
clear && fastboot reboot bootloader
clear && fastboot reboot fastboot
clear && fastboot flash --disable-verity --disable-verification boot boot.img
clear && fastboot flash dtbo dtbo.img
clear && fastboot flash --disable-verity --disable-verification vbmeta vbmeta.img
clear && fastboot flash vendor vendor.img
clear && fastboot erase system
clear && fastboot delete-logical-partition product_a
clear && fastboot erase system
clear && fastboot flash system system.img
clear && fastboot -w
clear && fastboot reboot bootloader
clear && fastboot reboot
