#!/usr/bin/bash

clear
echo "*******************************************************"
echo "*                                                     *"
echo "* this script will return some values for you related *"
echo "* to the treble project                               *"
echo "*                                                     *"
echo "*******************************************************"

vendordevice=$(adb shell getprop ro.product.vendor.device)
trebleenabled=$(adb shell getprop ro.treble.enabled)
cpuarchitecture=$(adb shell getprop ro.product.cpu.abi)
boothardware=$(adb shell getprop ro.boot.hardware)
deviceminsdk=$(adb shell getprop ro.build.version.min_supported_target_sdk)
devicesdk=$(adb shell getprop ro.build.version.sdk)

echo ""
echo ""
echo "           DEVICE: $vendordevice"
echo "  SUPPORTS TREBLE: $trebleenabled"
echo " CPU ARCHITECTURE: $cpuarchitecture"
echo "    BOOT HARDWARE: $boothardware"
echo "   DEVICE MIN SDK: $deviceminsdk"
echo "       DEVICE SDK: $devicesdk (your current OS sdk)"
echo ""
